language: node_js
node_js:
  - 14
cache:
  directories:
  - node_modules
script:
  - npm install && npm run build && npm run build-addon && npm run package-addon
after_failure: cat /home/travis/.npm/_logs/*-debug.log
warnings_are_errors: false
env:
  CI=false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: html-src/build
  on:
    branch: master
